### ISSUE TITLE
void before an expression is misclassified as a variable

### ISSUE THREAD

**Issue by steve02081504** [Tatakinov/yayalint#4]
![图片](https://user-images.githubusercontent.com/31927825/179344838-fc92814f-53a6-45f7-892d-5b599d0fbc0f.png)
![图片](https://user-images.githubusercontent.com/31927825/179344862-6b9f006b-6d0e-47a8-88d7-39517657f637.png)
The void before the expression is used to discard the value of the expression from the return value candidate list
I think lint has misjudged here

**Comment by Tatakinov** [comment]
maybe fixed in v1.6.2.
