### ISSUE TITLE
Indicate the file and line number for dic or dicdir not found in include

### ISSUE THREAD

**Issue by steve02081504** [Tatakinov/yayalint#5]
If this is modified, we can lint the configuration file with the language IDs of `aya-dicdir-confing` and `aya-base-confing`!
![](https://user-images.githubusercontent.com/31927825/179355518-3573ad23-b1d1-48da-8f25-aa52aa6d0581.png)

**Comment by Tatakinov** [comment]
implemented in v1.6.3
